name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore: ['**.md', 'img/**']

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  pull-request-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Install packages
        run: yarn install

      - name: Compile
        run: yarn run compile

      - name: Install plugin
        run: |
          sf plugins link .
          sf plugins

      - name: Unit tests
        run: yarn run test:only
